### ISSUE TITLE
(question) how to disable cookie headers?

### ISSUE THREAD

**Issue by caspianite** [DemonMartin/tlsClient#1]
when i send a request, there are multiple "cookie" header entries (even with defaultheaders set to {}), is there any way i can send with cookies, but without these headers? stock request to emulate has no "cookie" header
![immagine](https://github.com/DemonMartin/tlsClient/assets/122411998/d9baa25b-a759-454c-9d29-6309bbd5a404)

**Comment by DemonMartin** [comment]
By default, the tlsClientWrapper uses the same session between all requests.

Cookies are shared between the session by tlsClient hence why there are unexpected cookies in your request.

When defining the tlsClientWrapper Class, set `rotateSessions: true` or disable the defaultCookieJar.

If I misunderstood your issue, please feel free to further explain me your problem.

**Comment by caspianite** [comment]
that was it, ty!
