### ISSUE TITLE
Can't bypass cloudflare's protection

### ISSUE THREAD

**Issue by wwangyu2** [DemonMartin/tlsClient#3]
![image](https://github.com/DemonMartin/tlsClient/assets/129188737/a765a408-f1e0-40af-a1ad-3d22fc511e05)

URL: `https://www.eleze.top/`

code：
```
import tlsClient from 'tlsclientwrapper';
const client = new tlsClient();

console.log(await client.get("https://www.eleze.top/"));
```

Can you give an example of how to bypass cloudflare protection?

**Comment by DemonMartin** [comment]
Hey! I think you misunderstand what `tlsclientwrapper` is for.

It's a simple Wrapper for the TLSClient Libs created by @bogdanfinn. It does not in any way "bypass cloudflare protection".
The requests have a valid TLS Signature which are realistic, but it cannot solve JavaScript related Challenges.

For that, you can probably use something like https://scrappey.com/ by @Pim97.

(p.s, you need to call client.terminate() at the End to terminate the workerpool)
