### ISSUE TITLE
Crash during the launch of any request

### ISSUE THREAD

**Issue by mirikqq** [DemonMartin/tlsClient#5]
I'm trying to run the code from the example, but the application crashes (without errors, just crash, last node logs message npm verb exit 3221226356)
Mb need to install some deps like any dll or go libs?
Running via node index.js

node ver: v20.11.0
os: win11 x64

index.js
```
import tlsClient from "tlsclientwrapper";
const client = new tlsClient();

console.log(await client.get("https://example.com/"));

```

package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "tlsclientwrapper": "^1.4.3"
  }
}

```

**Comment by DemonMartin** [comment]
`ffi-rs` seems to have changed something which causes all fresh installations to not correctly work.

I have pushed a new Update `v2.0.0` where I switched from ffi-rs to koffi. Please try the new Version and let me know if that fixed your Issue.

**Comment by mirikqq** [comment]
> `ffi-rs` seems to have changed something which causes all fresh installations to not correctly work.
> 
> I have pushed a new Update `v2.0.0` where I switched from ffi-rs to koffi. Please try the new Version and let me know if that fixed your Issue.

Yep, it works
